driver:
  name: vagrant
  product: chef

chef_versions:
- 13

platforms:
- name: ubuntu-18.04
  run_list:
  - recipe[apt]
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[supervisor]
  attributes:
    poise-python:
      options:
        pip_version: '9.0.3'
